// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYDMPcxHdulmhG9689Qee_G7dU_OZWJXQ',
    appId: '1:35557516128:web:eecae2a14e806f23543405',
    messagingSenderId: '35557516128',
    projectId: 'dalel-a19a6',
    authDomain: 'dalel-a19a6.firebaseapp.com',
    storageBucket: 'dalel-a19a6.appspot.com',
    measurementId: 'G-SCCVVFT7ZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNtfVC5mcQzPF-rkaVCyxC69ZsW5ubbbk',
    appId: '1:35557516128:android:5cf407d1a60081cb543405',
    messagingSenderId: '35557516128',
    projectId: 'dalel-a19a6',
    storageBucket: 'dalel-a19a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAROA9IHmpZBfMLlhymSb2HMOmiGe8lfks',
    appId: '1:35557516128:ios:233948c6278bc1b9543405',
    messagingSenderId: '35557516128',
    projectId: 'dalel-a19a6',
    storageBucket: 'dalel-a19a6.appspot.com',
    iosBundleId: 'com.example.dalel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAROA9IHmpZBfMLlhymSb2HMOmiGe8lfks',
    appId: '1:35557516128:ios:233948c6278bc1b9543405',
    messagingSenderId: '35557516128',
    projectId: 'dalel-a19a6',
    storageBucket: 'dalel-a19a6.appspot.com',
    iosBundleId: 'com.example.dalel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYDMPcxHdulmhG9689Qee_G7dU_OZWJXQ',
    appId: '1:35557516128:web:9b523ac9434d1d3a543405',
    messagingSenderId: '35557516128',
    projectId: 'dalel-a19a6',
    authDomain: 'dalel-a19a6.firebaseapp.com',
    storageBucket: 'dalel-a19a6.appspot.com',
    measurementId: 'G-ZVMWQJWPZJ',
  );
}
